--Recommended to set the same number of options on each suit to false to keep the deck menu aligned. Pokemon listed in the second column are also on that entry.

return {
-- All suits 
    ["eevee"] = true,
    ["unown"] = true,
    ["burmy"] = true,		--No Spades on Burmy
    ["rotom"] = true,
    ["deerling"] = true,
    ["vivillon"] = true,
    ["flabebe"] = true,
    ["oricorio"] = true, 		--squawkabilly
    ["ogerpon"] = true,

--Spades
    ["squirtle"] = true,
    ["nidoran"] = true,
    ["jigglypuff"] = true,
    ["zubat"] = true,
    ["venonat"] = true,
    ["poliwag"] = true,
    ["tentacool"] = true,
    ["grimer"] = true,
    ["gastly"] = true,
    ["horsea"] = true,
    ["magikarp"] = true,
    ["shellder"] = true,		--lapras
    ["omanyte"] = true,
    ["articuno"] = true,
    ["mewtwo"] = true,			--mew
    ["totodile"] = true,
    ["hoothoot"] = true,
    ["marill"] = true,
    ["wooper"] = true,
    ["murkrow"] = true,
    ["wobbuffet"] = true,
    ["gligar"] = true,			--skorupi
    ["qwilfish"] = true,
    ["lugia"] = true,			--mantine
    ["mudkip"] = true,
    ["lotad"] = true,
    ["wingull"] = true,			--ducklett and sandygast
    ["nosepass"] = true,		--glimmet
    ["mawile"] = true,			--falinks
    ["volbeat"] = true,			--kricketot
    ["carvanha"] = true,
    ["wailmer"] = true,			--relicanth
    ["swablu"] = true,
    ["seviper"] = true,			--zangoose
    ["barboach"] = true,		--wishiwashi
    ["absol"] = true,			--chienpao
    ["snorunt"] = true,
    ["spheal"] = true,
    ["clamperl"] = true,
    ["beldum"] = true,
    ["kyogre"] = true,
    ["piplup"] = true,
    ["cranidos"] = true,
    ["shellos"] = true,
    ["gible"] = true,
    ["riolu"] = true,
    ["finneon"] = true,			--manaphy and phione
    ["dialga"] = true,			--azelf
    ["oshawott"] = true,
    ["purrloin"] = true,
    ["blitzle"] = true,
    ["roggenrola"] = true,
    ["tirtouga"] = true,
    ["minccino"] = true,		--indeedee
    ["vanillite"] = true,
    ["klink"] = true,
    ["tynamo"] = true,
    ["litwick"] = true,
    ["cubchoo"] = true,
    ["durant"] = true,			--heatmor and genesect
    ["deino"] = true,
    ["cobalion"] = true,
    ["thundurus"] = true,
    ["kyurem"] = true,			--reshiram and zekrom
    ["froakie"] = true,
    ["espurr"] = true,
    ["inkay"] = true,
    ["clauncher"] = true,		--wimpod
    ["bergmite"] = true,
    ["popplio"] = true,
    ["crabrawler"] = true,
    ["mareanie"] = true,
    ["typenull"] = true,
    ["cosmog"] = true,
    ["sobble"] = true,
    ["rookidee"] = true,
    ["nickit"] = true,
    ["cramorant"] = true,		--taillow
    ["sinistea"] = true,
    ["hatenna"] = true,
    ["eiscue"] = true,
    ["arctovish"] = true,		--dracozolt arctozolt dracovish
    ["calyrex"] = true,			--glastrier and spectrier
    ["quaxly"] = true,
    ["tatsugiri"] = true,		--veluza and dondozo
    ["frigibax"] = true,
    ["terapagos"] = true,


--Hearts
    ["charmander"] = true,
    ["pidgey"] = true,
    ["vulpix"] = true,
    ["paras"] = true,
    ["psyduck"] = true,
    ["growlithe"] = true,
    ["machop"] = true,
    ["ponyta"] = true,
    ["drowsee"] = true,			--munna
    ["krabby"] = true,
    ["exeggcute"] = true,
    ["hitmon"] = true,
    ["chansey"] = true,
    ["goldeen"] = true,			--chiyu
    ["mime"] = true,
    ["jynx"] = true,
    ["magmar"] = true,
    ["pinsir"] = true,			--ledyba
    ["porygon"] = true,
    ["kabuto"] = true,
    ["moltres"] = true,
    ["cyndaquil"] = true,
    ["sentret"] = true,			--pachirisu and skwovet
    ["togepi"] = true,
    ["snubbull"] = true,
    ["sneasel"] = true,
    ["teddiursa"] = true,
    ["slugma"] = true,			--torkoal and turtonator
    ["houndour"] = true,
    ["hooh"] = true,			--spearow and chingling
    ["torchic"] = true,
    ["zigzagoon"] = true,
    ["ralts"] = true,
    ["sableye"] = true,
    ["meditite"] = true,		--mienfoo
    ["numel"] = true,
    ["spoink"] = true,
    ["anorith"] = true,
    ["luvdisc"] = true,			--alomomola
    ["bagon"] = true,
    ["lati"] = true,
    ["groudon"] = true,
    ["chimchar"] = true,
    ["buneary"] = true,
    ["croagunk"] = true,
    ["palkia"] = true,
    ["darkrai"] = true,			--yveltal
    ["tepig"] = true,
    ["woobat"] = true,			--noibat
    ["drilbur"] = true,
    ["venipede"] = true,
    ["darumaka"] = true,
    ["zorua"] = true,
    ["gothita"] = true,
    ["foongus"] = true,
    ["frillish"] = true,
    ["rufflet"] = true,
    ["larvesta"] = true,
    ["fennekin"] = true,
    ["fletchling"] = true,
    ["spritzee"] = true,		--swirlix
    ["skrelp"] = true,
    ["tyrunt"] = true,
    ["xerneas"] = true,
    ["diancie"] = true,
    ["litten"] = true,
    ["rockruff"] = true,
    ["mudbray"] = true,
    ["fomantis"] = true,
    ["salandit"] = true,		--heatran
    ["bounsweet"] = true,
    ["enamorus"] = true,		--tapu koko and tapu lele
    ["poipole"] = true,
    ["scorbunny"] = true,
    ["wooloo"] = true,
    ["applin"] = true,
    ["impidimp"] = true,
    ["milcery"] = true,
    ["zacian"] = true,			--zamazenta and eternatus
    ["kubfu"] = true,			--pancham sawk and throh
    ["fuecoco"] = true,
    ["lechonk"] = true,
    ["tandemaus"] = true,
    ["flittle"] = true,
    ["finizen"] = true,
    ["koraidon"] = true,		--miraidon and cyclizar


--Clubs
    ["bulbasaur"] = true,
    ["caterpie"] = true,
    ["sandshrew"] = true,
    ["clefairy"] = true,
    ["oddish"] = true,
    ["diglett"] = true,
    ["bellsprout"] = true,
    ["geodude"] = true,
    ["farfetchd"] = true,
    ["doduo"] = true,
    ["onix"] = true,
    ["cubone"] = true,			--kangaskhan
    ["koffing"] = true,
    ["rhyhorn"] = true,
    ["tangela"] = true,			--carnivine
    ["ditto"] = true,
    ["snorlax"] = true,
    ["dratini"] = true,
    ["chikorita"] = true,
    ["spinarak"] = true,		--yanma
    ["chinchou"] = true,		--tadbulb
    ["natu"] = true,
    ["sudowoodo"] = true,
    ["hoppip"] = true,
    ["misdreavus"] = true,
    ["pineco"] = true,			--ferroseed
    ["heracross"] = true,
    ["remoraid"] = true,		--clobbopus
    ["smeargle"] = true,		--furfrou and shroodle
    ["larvitar"] = true,
    ["celebi"] = true,			--sunkern
    ["treecko"] = true,
    ["poochyena"] = true,		--maschiff
    ["wurmple"] = true,
    ["seedot"] = true,			--shroomish
    ["skitty"] = true,			--aipom
    ["roselia"] = true,
    ["gulpin"] = true, 			--wochien
    ["trapinch"] = true,
    ["cacnea"] = true,			--maractus and capsakid
    ["lileep"] = true,
    ["shuppet"] = true,
    ["rayquaza"] = true,
    ["turtwig"] = true,
    ["bidoof"] = true,
    ["combee"] = true,
    ["cherubi"] = true,
    ["snover"] = true,
    ["snivy"] = true,
    ["patrat"] = true,
    ["timburr"] = true,
    ["tympole"] = true,
    ["sewaddle"] = true,
    ["petilil"] = true,			--cottonee
    ["basculin"] = true,
    ["archen"] = true,
    ["trubbish"] = true,
    ["solosis"] = true,
    ["karrablast"] = true,		--shelmet
    ["axew"] = true,
    ["golett"] = true,
    ["virizion"] = true,		--drampa
    ["tornadus"] = true,
    ["meloetta"] = true,
    ["chespin"] = true,
    ["skiddo"] = true,
    ["goomy"] = true,
    ["phantump"] = true,		--pumpkaboo
    ["zygarde"] = true,
    ["rowlet"] = true,
    ["grubbin"] = true,
    ["dewpider"] = true,
    ["morelull"] = true,
    ["stufful"] = true,
    ["oranguru"] = true,		--passimian and komala
    ["meltan"] = true,
    ["grookey"] = true,
    ["rolycoly"] = true,
    ["cufant"] = true,
    ["dreepy"] = true,
    ["sprigatito"] = true,
    ["smoliv"] = true,
    ["bramblin"] = true,		--rellor
    ["tinkatink"] = true,
    ["varoom"] = true,
    ["pecharunt"] = true,


--Diamonds
    ["weedle"] = true,
    ["rattata"] = true,
    ["ekans"] = true,
    ["pikachu"] = true,
    ["meowth"] = true,
    ["mankey"] = true,
    ["abra"] = true,
    ["slowpoke"] = true,
    ["magnemite"] = true,
    ["seel"] = true, 			--cetoddle
    ["voltorb"] = true,
    ["staryu"] = true,
    ["scyther"] = true,
    ["electabuzz"] = true,
    ["tauros"] = true, 			--miltank bouffanlant
    ["aerodactyl"] = true,
    ["zapdos"] = true,
    ["mareep"] = true,
    ["girafarig"] = true,
    ["dunsparce"] = true,
    ["swinub"] = true,
    ["corsola"] = true,
    ["phanpy"] = true,
    ["stantler"] = true,
    ["slakoth"] = true,
    ["nincada"] = true, 		--nymble
    ["whismur"] = true,
    ["makuhita"] = true,
    ["aron"] = true,
    ["electrike"] = true, 		--yamper
    ["plusle"] = true, 			--minun
    ["solrock"] = true, 		--lunatone and minior
    ["corphish"] = true, 		--dwebble
    ["baltoy"] = true, 			--spiritomb
    ["feebas"] = true,
    ["duskull"] = true,
    ["deoxys"] = true,	 		--regigigas
    ["starly"] = true,
    ["shinx"] = true,
    ["shieldon"] = true,
    ["buizel"] = true,
    ["drifloon"] = true,
    ["stunky"] = true,
    ["bronzor"] = true, 		--tinglu
    ["hippopotas"] = true,
    ["giratina"] = true,
    ["lillipup"] = true,
    ["pansage"] = true, 		--all elemental monkies
    ["pidove"] = true,
    ["audino"] = true, 			--hoopa and magearna
    ["sandile"] = true,
    ["scraggy"] = true,
    ["yamask"] = true,
    ["joltik"] = true, 			--tarountula
    ["elgyem"] = true,
    ["pawniard"] = true,
    ["vullaby"] = true, 		--stonjourner
    ["terrakion"] = true,
    ["landorus"] = true,
    ["bunnelby"] = true,
    ["litleo"] = true,
    ["honedge"] = true,
    ["binacle"] = true, 		--dhelmise and arrokuda
    ["helioptile"] = true,
    ["amaura"] = true,
    ["pikipek"] = true,
    ["yungoos"] = true,
    ["cutiefly"] = true,
    ["pyukumuku"] = true, 		--pincurchin
    ["jangmoo"] = true,
    ["xurkitree"] = true, 		--regieleki
    ["necrozma"] = true,
    ["blipbug"] = true,
    ["chewtle"] = true,
    ["silicobra"] = true,
    ["toxel"] = true,
    ["sizzlipede"] = true,
    ["snom"] = true,
    ["morpeko"] = true,
    ["duraludon"] = true,
    ["pawmi"] = true,
    ["nacli"] = true,
    ["charcadet"] = true,
    ["wattrel"] = true, 		--zeraora
    ["greavard"] = true,
    ["gimmighoul"] = true,
}